[package]
name = "gvpaint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "1.0.10"
# rand = "0.8.5"
crossterm = "0.25.0"
termios = "0.3.3"
