[package]
name = "gvpaint"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "3.0.0"
# rand = "0.8.5"
crossterm = "0.28.1"
image = "0.25.5"
